name: freemework_cancellation
description: Set of various cancellation token sources
version: 0.1.1
homepage: https://freemework.org
repository: https://github.com/freemework/dart.cancellation
issue_tracker: https://github.com/freemework/dart.cancellation/issues
documentation: https://freemework.org/#cancellation?lang=dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freemework: ^0.1.1

dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
