name: freemework_cancellation
description: Set of various cancellation token sources
version: 0.2.0
homepage: https://freemework.org
repository: https://github.com/freemework/dart.cancellation
issue_tracker: https://github.com/freemework/dart.cancellation/issues
documentation: https://freemework.org/#cancellation?lang=dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freemework: ^0.2.0

dev_dependencies:
  build_runner: ^2.0.6
  build_test: ^2.1.2
  pedantic: ^1.11.1
  test: ^1.17.10
