name: freemework_cancellation
description: Set of various cancellation token sources of the Freemework
version: 0.0.1
homepage: https://freemework.org
repository: https://github.com/freemework/dart.cancellation
issue_tracker: https://github.com/freemework/dart.cancellation/issues
documentation: https://freemework.org/#cancellation?lang=dart

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  freemework: ^0.0.1

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  pedantic: ^1.9.2
  test: ^1.15.7
